services:
  mysql:
    image: mysql:8.0
    container_name: bookweave-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: X1624TMGMMySQLPablo$
      MYSQL_DATABASE: bookweave
      MYSQL_USER: pabloroldao
      MYSQL_PASSWORD: X1624TMGMMySQLPablo$
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookweave-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookweave-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookweave
      SPRING_DATASOURCE_USERNAME: pabloroldao
      SPRING_DATASOURCE_PASSWORD: X1624TMGMMySQLPablo$
    networks:
      - bookweave-net

volumes:
  mysql_data:

networks:
  bookweave-net:
