INSERT INTO genres (id, name) VALUES
(1, 'Science Fiction'),
(2, 'Fantasy'),
(3, 'Mystery'),
(4, 'Romance'),
(5, 'Historical Fiction'),
(6, 'Thriller'),
(7, 'Horror'),
(8, 'Biography'),
(9, 'Self-Help'),
(10, 'Poetry'),
(11, 'Drama'),
(12, 'Adventure'),
(13, 'Dystopian'),
(14, 'Young Adult'),
(15, 'Philosophy'),
(16, 'Graphic Novel'),
(17, 'Cyberpunk'),
(18, 'Paranormal'),
(19, 'Magical Realism'),
(20, 'Satire');